/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        brand: {
          DEFAULT: 'var(--brand)',
          hover: 'var(--brand-hover)',
          light: 'var(--brand-light)',
          dark: 'var(--brand-dark)',
        },
        paper: 'var(--color-paper)',
        surface: 'var(--color-surface)',
        'surface-alt': 'var(--surface-alt)',
        rule: 'var(--color-rule)',
        line: 'var(--color-line)',
        'border-light': 'var(--border-light)',
        ink: 'var(--color-ink)',
        muted: 'var(--color-muted)',
        'neutral-400': '#767676',
        terracotta: {
          DEFAULT: 'var(--color-terracotta)',
          hover: 'var(--color-terracotta-hover)',
          soft: 'var(--color-terracotta-soft)',
        },
        cognac: {
          DEFAULT: 'var(--color-terracotta)',
          dark: 'var(--color-terracotta-hover)',
          soft: 'var(--color-terracotta-soft)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          soft: 'var(--color-success-soft)',
        },
        danger: {
          DEFAULT: 'var(--color-danger)',
          soft: 'var(--color-danger-soft)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          soft: 'var(--color-warning-soft)',
        },
      },
      fontFamily: {
        sans: [
          'Poppins',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'Helvetica',
          'Arial',
          'sans-serif',
        ],
        display: ['TripSans', 'Poppins', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['TripSans', 'serif'],
      },
      spacing: {
        'tight-val': 'var(--spacing-tight-val)',
        'standard-val': 'var(--spacing-standard-val)',
        'loose-val': 'var(--spacing-loose-val)',
        'hero-val': 'var(--spacing-hero-val)',
        'footer-val': 'var(--spacing-footer-val)',
        'card-micro': 'var(--card-gap-micro)',
        'card-small': 'var(--card-gap-small)',
        'gap-micro': 'var(--gap-micro-val)',
        'gap-standard': 'var(--gap-standard-val)',
        'gap-section': 'var(--gap-section-val)',
        'gap-major': 'var(--gap-major-val)',
        'section-footer': 'var(--spacing-footer-val)',
        'space-1': '0.25rem',
        'space-2': '0.5rem',
        'space-3': '0.75rem',
        'space-4': '1rem',
        'space-6': '1.5rem',
        'space-8': '2rem',
        'space-12': '3rem',
        'space-16': '4rem',
        'space-24': '6rem',
      },
      maxWidth: {
        layout: '1800px',
        editorial: '1800px',
      },
      borderRadius: {
        none: '0',
        control: 'var(--radius-control)',
        image: 'var(--radius-image)',
        pill: 'var(--radius-pill)',
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
      },
      boxShadow: {
        premium: 'var(--shadow-premium)',
        card: 'var(--shadow-card)',
        xs: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
        sm: '0 1px 3px 0 rgba(0, 0, 0, 0.08)',
        md: '0 4px 6px -1px rgba(0, 0, 0, 0.07)',
      },
      transitionDuration: {
        control: 'var(--duration-control)',
        accordion: 'var(--duration-accordion)',
        hero: 'var(--duration-hero)',
      },
    },
  },
  plugins: [],
}
